#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

exec < /dev/tty && npx cz --hook || true
# exec < /dev/tty && node_modules/.bin/cz --hook || true
# exec < /dev/tty && git cz --hook || true"
